spring:
  application:
    name: auth-service

server:
  port: 8081

app:
  user-service:
    url: http://localhost:8082

jwt:
  access-key: ${JWT_ACCESS_KEY}
  access-exp-minutes: 60
  service-exp-minutes: 5
open:
  api:
    title: Auth Service API
    version: v1
    description: Authentication & JWT endpoints
    server-url: http://localhost:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO

