management:
  server:
    port: 8888
  endpoints:
    web:
      base-path: /internal/actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: auth-service


logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: ERROR

spring:
  lifecycle:
    #Chờ request thêm 30s trước khi shutdown nếu ko shutdown liền sẽ bị mất request
    timeout-per-shutdown-phase: 30s

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false