image: maven:3.9.6-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SPRING_PROFILES_ACTIVE: ci
  AUTH_APP_NAME: auth-service
  USER_APP_NAME: user-service

cache:
  key: maven-cache
  paths:
    - .m2/repository

stages:
  - test
  - build
  - deploy

test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  tags:
    - local
  services:
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    TESTCONTAINERS_HOST_OVERRIDE: docker
  script:
    - chmod +x mvnw
    - ./mvnw test -pl auth-service -am
    - ./mvnw test -pl user-service -am
  artifacts:
    when: always
    reports:
      junit:
        - auth-service/target/surefire-reports/*.xml
        - user-service/target/surefire-reports/*.xml

build-job:
  stage: build
  tags:
    - local
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - core/target/*.jar
      - auth-service/target/*.jar
      - user-service/target/*.jar
    expire_in: 1 hour

deploy-job:
  stage: deploy
  image: docker:24
  services:
    - name: docker:24-dind
      alias: docker
  tags:
    - local
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - build-job
  only:
    - main
    - review/r4
  script:
    - 'AUTH_JAR=$(ls auth-service/target/*.jar | head -n 1)'
    - 'USER_JAR=$(ls user-service/target/*.jar | head -n 1)'
    - 'echo "Using auth jar: $AUTH_JAR"'
    - 'echo "Using user jar: $USER_JAR"'
    - 'docker rm -f "$AUTH_APP_NAME" || true'
    - 'docker rm -f "$USER_APP_NAME" || true'
    - |
      docker run -d \
        --name "$AUTH_APP_NAME" \
        -p 8080:8080 \
        -v "$CI_PROJECT_DIR/$AUTH_JAR:/app.jar" \
        mcr.microsoft.com/openjdk/jdk:17-ubuntu \
        java -jar /app.jar
    - |
      docker run -d \
        --name "$USER_APP_NAME" \
        -p 8081:8080 \
        -v "$CI_PROJECT_DIR/$USER_JAR:/app.jar" \
        mcr.microsoft.com/openjdk/jdk:17-ubuntu \
        java -jar /app.jar