version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "55432:5432"

    volumes:
      #named volume:map volume postgres_data đã tạo ở câu lệnh dưới cùng vào trong container tại: /var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
      #Bind mount: gắn file init.sql ở máy vào docker ở /docker-entrypoint-initdb.d/init.sql vì thư mục /docker-entrypoint-initdb.d
      #trong postgres nên nó sẽ có cơ chế hoạt động là khi chưa có database nó sẽ chạy init.sql còn nếu có sẽ ko chạy nx
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    #Đợi DB READY rồi mới cho service start.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    #Mỗi 5s test DB coi database sẵn sàng chưa
      interval: 5s
    #Nếu 5s ko trả lời thì fail
      timeout: 5s
    #Fail 5 lần → container = unhealthy. Lúc này các service depends_on database sẽ ko chạy đc
      retries: 5


  auth-service:
    build: ./auth-service
    container_name: auth-service
    #Crash → tự restart.
    restart: always

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${AUTH_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}

    ports:
      - "8081:8081"

    depends_on:
      postgres:
        condition: service_healthy


  user-service:
    build: ./user-service
    container_name: user-service
    restart: always

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${USER_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}

    ports:
      - "8082:8082"

    depends_on:
      postgres:
        condition: service_healthy

#Tạo volume trong docker, docker tự quản lý chỗ lưu mình ko cần quan tâm
#Giống mình chạy lệnh docker volume create postgres_data
volumes:
  postgres_data: