spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      #số request đồng thời đến database là 10 ->request thứ 11 phải chờ
      maximum-pool-size: 10
      #số connection luôn mở sẵn là 3 dù ko ai dùng. Vì mở connection mới = chậm (TCP + auth + handshake). Mở sẵn giúp giảm lag
      minimum-idle: 3
      #Nếu connection không xài trong 30s → đóng.
      idle-timeout: 30000
      #1 connection sống tối đa 30 phút → reset. Dù đang khỏe cũng cho nghỉ.
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  server:
    port: 8888
  endpoints:
    web:
      base-path: /internal/actuator
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: INFO