spring:
  application:
    name: user-service

server:
  port: 8082

app:
  auth-service:
    url: http://localhost:8081

jwt:
  access-key: ${JWT_ACCESS_KEY}

open:
  api:
    title: User Service API
    version: v1
    description: User management endpoints
    server-url: http://localhost:8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


























